Updated shipment event with document references and references
dcsaorg/DCSA-Event-Core pull request #15
Opened 2021-07-19 11:56 UTC by douradofrazer

Resolves:
https://dcsa.atlassian.net/browse/DDT-28

2021-07-19 12:11 UTC, nt-as requested changes

2021-07-19 12:11 UTC, nt-as commented on src/main/java/org/dcsa/core/events/repository/ReferenceRepository.java
> +  Flux<Reference> findByCarrierBookingReference(String carrierBookingReference);
This is too simple - it should also find references on transport document related to that shipment.  This query should look similar to the one for `findByShipmentID` (plus JOIN to `shipment` so you can use `carrier_booking_reference` in the `WHERE` clause)

2021-07-19 12:11 UTC, nt-as commented on src/main/java/org/dcsa/core/events/repository/ShipmentEventRepository.java
> +  Flux<String> findTransportDocumentRefsByShipmentId(UUID shipmentId);
```suggestion
          + "WHERE ci.shipment_id = :shipmentID")
  Flux<String> findTransportDocumentRefsByShipmentID(UUID shipmentID);
```
(Will need changes to the caller as well)

2021-07-19 12:11 UTC, nt-as commented on src/main/java/org/dcsa/core/events/repository/ShipmentEventRepository.java
> +  Flux<String> findCarrierBookingRefsByShipmentId(UUID shipmentId);
```suggestion
          + "WHERE s.id = :shipmentID")
  Flux<String> findCarrierBookingRefsByShipmentID(UUID shipmentID);
```

Remember to update callers as well (not covered in my review)

2021-07-19 12:11 UTC, nt-as commented on src/main/java/org/dcsa/core/events/service/impl/ShipmentEventServiceImpl.java
> +                        .subscribe());
`.subscribe()` cannot be used here - it will resolve "too late".

Replace the `.doOnNext` on l46 instead with a `.flatMap` and return the Mono returned by `transformDocRefs` instead (possibly chaining into a `.thenReturn` if you need to change the type).

2021-07-19 12:11 UTC, nt-as commented on src/main/java/org/dcsa/core/events/service/impl/ShipmentEventServiceImpl.java
> +                        .subscribe());
Ditto (subscribe)

2021-07-19 12:11 UTC, nt-as commented on src/main/java/org/dcsa/core/events/service/impl/ShipmentEventServiceImpl.java
> +                        .subscribe());
Ditto (subscribe)

2021-07-19 12:11 UTC, nt-as commented on src/main/java/org/dcsa/core/events/service/impl/ShipmentEventServiceImpl.java
> +        return Mono.justOrEmpty(shipmentEvent);
```suggestion
        return Mono.just(shipmentEvent);
```

2021-07-19 12:11 UTC, nt-as commented on src/main/java/org/dcsa/core/events/service/impl/ShipmentEventServiceImpl.java
> +                                Flux.just(se.getDocumentID())))
The carrier booking references should be tagged as BKG and not TRD.

2021-07-19 12:11 UTC, nt-as commented on src/main/java/org/dcsa/core/events/service/impl/ShipmentEventServiceImpl.java
> +                                Flux.just(se.getDocumentID())))
The transport document references should be tagged as TRD and not BKG.

2021-07-19 12:11 UTC, nt-as commented on src/main/java/org/dcsa/core/events/service/impl/ShipmentEventServiceImpl.java
> +                                    se.getShipmentID())))
As mentioned earlier, I do not think we should use `SHI` here.  Instead BKG + TRD (in that order).

2021-07-20 06:30 UTC, nt-as approved these changes
Approved with one "should be fix but can be fixed later" remark.

2021-07-20 06:30 UTC, nt-as commented on src/main/java/org/dcsa/core/events/repository/ReferenceRepository.java
> +          + "JOIN shipment s ON shipment_id = s.id "
Should probably be a `LEFT JOIN` as otherwise the reference is filtered out even if there is a valid shipping instruction ID for it (because it cannot `JOIN` with `shipment`).

(This might be a general mistake in more queries - if so, please fix them where you spot them).

Note that I am approving despite of this remark because I think we can fix this afterwards and I suspect you did not introduce this bug.

2021-07-20 07:45 UTC, douradofrazer commented on src/main/java/org/dcsa/core/events/repository/ReferenceRepository.java
> +          + "JOIN shipment s ON shipment_id = s.id "
You're right , I updated it for this query. I will update others as I spot them.

2021-07-20 07:55 UTC, nt-as approved these changes

2021-07-20 07:55 UTC, merged