Align ActiveReeferSettings, CargoItem, and Ref with IM
dcsaorg/DCSA-Event-Core pull request #205
Opened 2022-02-10 14:28 UTC by mp-assco

2022-02-10 14:33 UTC, HenrikHL commented on src/main/java/org/dcsa/core/events/model/Reference.java
>    @Size(max = 100)
We need a @NotNull here

2022-02-10 14:35 UTC, mp-assco commented on src/main/java/org/dcsa/core/events/model/Reference.java
>    @Size(max = 100)
Done

2022-02-10 15:14 UTC, HenrikHL submitted a review, later dismissed
LGTM

2022-02-11 09:11 UTC, douradofrazer requested changes

2022-02-11 09:11 UTC, douradofrazer commented on src/main/java/org/dcsa/core/events/model/ActiveReeferSettings.java
> +public class ActiveReeferSettings extends AuditBase implements Persistable<UUID> {
Could you remove AuditBase?  we do not use it.

2022-02-11 09:11 UTC, douradofrazer commented on src/main/java/org/dcsa/core/events/model/ActiveReeferSettings.java
> +    @JsonIgnore
No need for @JsonIgnore,  we have separated entities and DTOs

2022-02-11 09:36 UTC, mp-assco commented on src/main/java/org/dcsa/core/events/model/ActiveReeferSettings.java
> +    @JsonIgnore
Done

2022-02-11 09:36 UTC, mp-assco commented on src/main/java/org/dcsa/core/events/model/ActiveReeferSettings.java
> +public class ActiveReeferSettings extends AuditBase implements Persistable<UUID> {
Done

2022-02-11 11:32 UTC, pimg approved these changes

2022-02-11 11:34 UTC, merged