Reduce the use of DCSA-Core in cases where it is not necessary
dcsaorg/DCSA-Event-Core pull request #212
Opened 2022-02-15 14:59 UTC by nt-as

These commits will enable the removal/scope reduction of:

- `BaseService` (removal)
- `ExtendedBaseService` reduced to `findAllExtended`
- `BaseController` (removal)
- `ExtendedBaseController` reduced a `@GetMapping` for getting all entities

Some repositories have also been updated to remove unused methods or reduce their scope so they no longer extend `ExtendedRepository`.

2022-02-15 15:32 UTC, pimg requested changes

2022-02-15 15:32 UTC, pimg commented on src/main/java/org/dcsa/core/events/service/FacilityService.java
>  public interface FacilityService extends ExtendedBaseService<Facility, UUID> {
shouldn't the extends ExtendedBaseService be removed?

2022-02-15 15:32 UTC, pimg commented on src/main/java/org/dcsa/core/events/service/TimestampDefinitionService.java
>  public interface TimestampDefinitionService extends ExtendedBaseService<TimestampDefinition, String> {
shouldn't extends ExtendedBaseService be removed?

2022-02-15 15:32 UTC, pimg commented on src/main/java/org/dcsa/core/events/service/VesselService.java
>  public interface VesselService extends ExtendedBaseService<Vessel, UUID> {
shouldn't extends ExtendedBaseService be removed

2022-02-15 15:36 UTC, nt-as commented on src/main/java/org/dcsa/core/events/service/FacilityService.java
>  public interface FacilityService extends ExtendedBaseService<Facility, UUID> {
No, UI Support (application supporting the UI) provides a facility controller that relies on the core features (filter + sorting).

2022-02-15 15:36 UTC, nt-as commented on src/main/java/org/dcsa/core/events/service/TimestampDefinitionService.java
>  public interface TimestampDefinitionService extends ExtendedBaseService<TimestampDefinition, String> {
No, UI Support (application supporting the UI) provides a timestamp definition controller that relies on the core features (filter + sorting).

2022-02-15 15:36 UTC, nt-as commented on src/main/java/org/dcsa/core/events/service/VesselService.java
>  public interface VesselService extends ExtendedBaseService<Vessel, UUID> {
No, UI Support (application supporting the UI) provides a vessel controller that relies on the core features (filter + sorting).

2022-02-16 07:33 UTC, pimg approved these changes

2022-02-16 07:44 UTC, merged