DDT-983: Fix for CreateConsignmentItem
dcsaorg/DCSA-Event-Core pull request #283
Opened 2022-04-01 06:43 UTC by mp-assco

2022-04-01 10:44 UTC, pimg requested changes
Changes appear good, but tests are missing

2022-04-04 07:02 UTC, mp-assco commented
> Changes appear good, but tests are missing

Done

2022-04-04 08:59 UTC, pimg requested changes

2022-04-04 08:59 UTC, pimg commented on src/main/java/org/dcsa/core/events/edocumentation/service/impl/ConsignmentItemServiceImpl.java
> +        .then(Mono.just(shippingInstructionReference));
why do we return a reference which is no longer present? Other delete operations return void

2022-04-04 09:03 UTC, mp-assco commented on src/main/java/org/dcsa/core/events/edocumentation/service/impl/ConsignmentItemServiceImpl.java
> +        .then(Mono.just(shippingInstructionReference));
I wrote about this in the DCSA chat, but didn't really get a reply. The `assertNext` fails in the unit test when you return `void` for some reason and the only way I could find around it was to return a value. Would prefer just returning void, but don't know how to prevent errors in the tests.

2022-04-04 10:53 UTC, pimg approved these changes

2022-04-04 10:54 UTC, merged