DDT-17-unofficial-APIs
dcsaorg/DCSA-Event-Core pull request #44
Opened 2021-08-17 12:46 UTC by Abdiiir

Relates to DDT-17-unofficial-APIs in OVS 

- The CarrierRepo is moved to Event-Core to allow for use in VesselServiceImp
- Carrier attribute is populated

2021-08-18 20:23 UTC, HenrikHL commented on src/main/java/org/dcsa/core/events/service/impl/VesselServiceImpl.java
> +        extendedRequest.parseParameter(Map.of("vesselIMONumber", List.of(String.valueOf(VesselIMONumber))));
@nt-as this seems somewhat overkill to me. Don't we support this in a more simple way?
(Maybe a simple vesselRepository.findById() followed by a "load-Carrier-information"...?)

2021-08-18 20:25 UTC, HenrikHL commented on src/main/java/org/dcsa/core/events/service/impl/VesselServiceImpl.java
> +        }
To me this code seems more suitable in a carrierService where you provide a codeList and a code - it then returns a carrier.
I am quite sure we need this other places than on vessel

2021-08-19 08:04 UTC, nt-as commented on src/main/java/org/dcsa/core/events/service/impl/VesselServiceImpl.java
> +        extendedRequest.parseParameter(Map.of("vesselIMONumber", List.of(String.valueOf(VesselIMONumber))));
No, we currently do not support this in a more simple way without re-implementing what ExtendedRequest does for us.  Perhaps we can add something to DCSA-Core to do this after we are done with the necessary changes for the Hamburg cluster.

2021-08-19 08:06 UTC, nt-as commented on src/main/java/org/dcsa/core/events/service/impl/VesselServiceImpl.java
> +        }
I do not disagree that your proposal would be cleaner.  However, the proposed code works and I think we should start here and improve later.

2021-08-19 08:09 UTC, HenrikHL commented on src/main/java/org/dcsa/core/events/service/impl/VesselServiceImpl.java
> +        }
Fine with me - we just have to remember to move this code when we do the issuer on eBL (it has a issuerCode and a issuerCodeListProvider) and needs to be done in the same way...

2021-08-19 08:12 UTC, nt-as commented on src/main/java/org/dcsa/core/events/service/impl/VesselServiceImpl.java
> +        }
Hmm, if you have concrete usage case in mind already for eBL, then I am more open for it.

2021-08-19 08:18 UTC, HenrikHL commented on src/main/java/org/dcsa/core/events/service/impl/VesselServiceImpl.java
> +        }
I have this:
![image](https://user-images.githubusercontent.com/3489388/130033512-27cb877a-0792-4bfd-bcea-9a2c996dc52f.png)

2021-08-19 08:18 UTC, HenrikHL commented on src/main/java/org/dcsa/core/events/service/impl/VesselServiceImpl.java
> +        }
Which would need the same code...

2021-08-19 15:28 UTC, HenrikHL commented on src/main/java/org/dcsa/core/events/service/impl/TransportCallTOServiceImpl.java
> +        transportCallTO.setVessel(transportCallTO.getVessel());
What does this do?

2021-08-19 15:45 UTC, HenrikHL commented
Apart from my comment above this LGTM

2021-08-19 16:02 UTC, nt-as commented on src/main/java/org/dcsa/core/events/service/impl/TransportCallTOServiceImpl.java
> +        transportCallTO.setVessel(transportCallTO.getVessel());
There is an assymmetri between the getters and setters.  I find it confusing as well but it is necessary right now (I will see if we can find a better solution for it).

2021-08-20 06:23 UTC, HenrikHL approved these changes

2021-08-20 07:49 UTC, merged

2021-08-20 07:56 UTC, douradofrazer requested changes

2021-08-20 07:56 UTC, douradofrazer commented on src/main/java/org/dcsa/core/events/repository/CarrierRepository.java
> +    Mono<Carrier> getCarrierBySMdgCode(String smdgCode);
```suggestion
    Mono<Carrier> findBySmdgCode(String smdgCode);
```

2021-08-20 07:56 UTC, douradofrazer commented on src/main/java/org/dcsa/core/events/repository/CarrierRepository.java
> +    Mono<Carrier> getCarrierByNmftaCode(String NmftaCode);
```suggestion
    Mono<Carrier> findByNmftaCode(String nmftaCode);
```

2021-08-20 07:56 UTC, douradofrazer commented on src/main/java/org/dcsa/core/events/repository/CarrierRepository.java
> +public interface CarrierRepository extends ExtendedRepository<Carrier, UUID> {
Use query methods instead of the @Query here.
You can remove `@Query(...)` if you use the suggestions mentioned below.

2021-08-20 08:09 UTC, nt-as commented on src/main/java/org/dcsa/core/events/repository/CarrierRepository.java
> +    Mono<Carrier> getCarrierByNmftaCode(String NmftaCode);
https://github.com/dcsaorg/DCSA-Event-Core/pull/46

2021-08-20 08:09 UTC, nt-as commented on src/main/java/org/dcsa/core/events/repository/CarrierRepository.java
> +public interface CarrierRepository extends ExtendedRepository<Carrier, UUID> {
https://github.com/dcsaorg/DCSA-Event-Core/pull/46